[[main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 1

[[main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 2

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 3

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 4

 
# Social Media Configuration
[[social]]
    identifier = "github"
    name = "GitHub"
    url = "#"
    weight = 1